# Generated by Django 4.0.4 on 2022-06-01 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_rename_listings_listing'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='starting_bid',
            new_name='bid',
        ),
    ]
