# Generated by Django 4.0.4 on 2022-06-03 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_bid_comment_delete_bids_delete_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=50)),
                ('listing', models.ManyToManyField(blank=True, related_name='categories', to='auctions.listing')),
            ],
        ),
    ]
