# Generated by Django 4.0.4 on 2022-06-07 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_rename_category_categories_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='category',
            field=models.CharField(choices=[('birds', 'birds'), ('puppies', 'puppies'), ('cats', 'cats'), ('rabbits', 'rabbits'), ('fishes', 'fishes'), ('turtles', 'turtles'), ('Others', 'Others')], default='Others', max_length=30),
        ),
    ]
