# Generated by Django 4.0.4 on 2022-06-07 13:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0011_remove_categories_listings_alter_listing_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.ForeignKey(choices=[('birds', 'birds'), ('puppies', 'puppies'), ('cats', 'cats'), ('rabbits', 'rabbits'), ('fishes', 'fishes'), ('turtles', 'turtles'), ('Others', 'Others')], default='Others', on_delete=django.db.models.deletion.CASCADE, to='auctions.categories'),
        ),
    ]
